language: android
android:
  components:
  - tools
  - platform-tools
install:
  - echo y | sdkmanager "ndk-bundle"
script:
  - curl -u xausky:$SYSKILLER_TOKEN https://syskiller.org/remote.php/webdav/xausky.jks -O
  - echo apiSecret=$FABRIC_APP_SECRET > app/fabric.properties
  - ./gradlew assembleRelease
deploy:
  skip_cleanup: true
  provider: releases
  draft: true
  api_key:
    secure: $GITHUB_RELEASE_TOKEN
  file: app/build/outputs/apk/release/app-release.apk
  on:
    tags: true
    repo: xausky/UnityModManager
after_success:
- curl -u xausky:$SYSKILLER_TOKEN -T app/build/outputs/apk/release/app-release.apk https://syskiller.org/remote.php/webdav/模组管理器/模组管理器-$TRAVIS_BRANCH.apk
