language: android
dd:
- openssl aes-256-cbc -K $encrypted_d5896aca80a4_key -iv $encrypted_d5896aca80a4_iv
  -in xausky.jks.enc -out ../xausky.jks -d
android:
  components:
  - tools
  - build-tools-26.0.2
  - platform-tools
  - android-26
script:
  - "./gradlew assembleRelease"